### Listar todas as tarefas
GET http://localhost:5000/api/chamado/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/chamado/cadastrar

###atualizar um chamado
PATCH http://localhost:5000/api/chamado/alterar


###listar chamado em aberto
GET: http://localhost:5000/api/chamado/abertos

###listar chamado resolvidos
GET: http: //localhost:5000/api/chamado/resolvidos



Content-Type: application/json

{
    "descricao": "Trocar memórias"
}